version: '3.1'

services:

  backend:
    image: monkeythedev/svelte-material-ui-website
    ports:
      - "3000:3000"
  nginx:
    image: nginx
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - "8080:80"
    environment:
      # - NGINX_HOST=foobar.com
      - NGINX_PORT=80
