version: '3.7'

services:

  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "80:80"
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on: 
      - backend
    networks:
      - webnet

  backend:
    container_name: backend
    build:
      context: ./finances
      dockerfile: ./docker/Dockerfile
    command: yarn start:dev
    ports:
      - "3000:3000"
    volumes: 
      - ./finances:/opt/app
      - /opt/app/node_modules
    networks:
      - webnet
    
  # caddy:
  #   image: caddy:alpine
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #     - "443:443"   
  #   volumes:
  #     - $PWD/caddy/Caddyfile:/etc/caddy/Caddyfile
  #     - $PWD/finances:/srv
  #     - ./caddy/caddy_data:/data
  #     - ./caddy/caddy_config:/config
  #   depends_on:
  #     - backend

volumes: 
  nginx:
  backend:

networks:
  webnet: