version: '3.1'

services:

  backend:
    build:
      context: ./finances
      dockerfile: ./docker/Dockerfile
    command: yarn start:dev
    ports:
      - "3000:3000"
    volumes: 
      - ./finances:/opt/app
      - /opt/app/node_modules
  nginx:
    image: nginx
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - "8080:80"
    environment:
      # - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    depends_on:
      - backend


volumes:
  database-data: